.gitignore, pyproject.toml
This PR makes a couple small changes for pypi, just changing the repo URL basically, and also adding Chenyang as an author.
- NA
=> Some small changes for pypi

README.md
Fix the image and video in our main README. This PR will resolve #245.
N/A
N/A
=> Fix media in README

README.md
Remove the audio track from our demo video
N/A
N/A
=> Remove audio from demo video

README.md
Adds a brief description to the top of the README.
=> Change title of README.md

README.md, prompt2model/dataset_generator/openai_gpt.py, prompt_exmaples.md, tests/dataset_generator_without_filter_test.py
Something like:
```
See more tips and tricks below:
* [Prompt Engineering](prompt_engineering.md)
```
- Foo
- Bar
- Baz
- NA
- (or link to PRs)
=> Add prompt examples

README.md
This changes the readme to reference the pypi package, not local.
- NA
=> Update README.md to reference pypi package

pyproject.toml
Add `protobuf==4.24.1` to the dependencies in pyproject.toml.
N/A
N/A
=> Add protobuf to dependencies

prompt2model/dataset_processor/base.py, prompt2model/dataset_processor/mock.py, prompt2model/dataset_retriever/hf_dataset_retriever.py, prompt2model/dataset_retriever/run_dataset_retriever.py, prompt2model/model_evaluator/base.py, prompt2model/model_evaluator/mock.py, prompt2model/model_retriever/base.py, prompt2model/model_retriever/mock.py, prompt2model/model_trainer/generate.py, prompt2model/param_selector/mock.py, prompt2model/run_locally.py
Several mypy errors were surfaced when adding an init file in #276 
This PR fixes all the types.
- NA
=> Fix mypy errors

tests/model_trainer_for_gpt_test.py
=> Fix typo in model_trainer_for_gpt_test.py

CONTRIBUTING.md, README.md
We now have a discord, so this adds it to our READMEs.
- NA
=> Added discord to readmes

README.md
I changed the end of the contribution.
- Foo
- Bar
- Baz
- NA
- (or link to PRs)
=> change end of contribution

prompt_examples.md
`ouput` is updated to `output` :D
=> Fix `prompt_examples.md` typo

.gitignore, notebook_demo.ipynb
This PR makes some revisions on the intro of the colab demo, up to the dataset retriever part.
@zhaochenyang20 : please review this and if it looks good merge this in to `add_colab_demo`, and then I would like to remove the mandatory command line manipulation from the various parts, starting with the dataset retriever: https://github.com/neulab/prompt2model/issues/292
- #290 
- NA
=> Revisions on intro of colab demo

.gitignore, notebook_demo.ipynb
This makes some wording modifications to the notebook demo.
I am done with checking through, so now I will actually try to run it on colab.
- NA
=> Wording modifications to notebook demo

prompt2model/dataset_retriever/description_dataset_retriever.py
This PR makes a directory for the dataset retriever file download if it doesn't exist already.
- Fixes https://github.com/neulab/prompt2model/issues/301
- NA
=> Make a directory for the dataset retriever

CONTRIBUTING.md, pyproject.toml
Better description/organization of developer install
https://github.com/neulab/prompt2model/issues/319
=> [refactoring] Adding dev dependencies

prompt2model/model_retriever/generate_hypothetical_document.py, prompt2model/utils/api_tools.py
#344 introduced a max_tokens configurable parameter for our LLM API wrapper, but this parameter is causing problems in our demo. This PR addresses those problems.
N/A
N/A
=> Fix bugs in API tools (to fix #348)

prompt2model/model_trainer/generate.py
Add support for trust_remote_code param for model trainer
https://github.com/neulab/prompt2model/issues/357
- NA
=> support for trust_remote_code param

prompt2model_demo.ipynb
Our notebook is currently broken due to an apparent markdown error. This PR fixes the notebook.
N/A
N/A
=> Fix notebook (currently broken)

.github/workflows/base_ci.yml
Create a reusable workflow which can be reused by future CI workflows.
I used https://docs.github.com/en/actions/using-workflows/reusing-workflows as a guide to do this.
N/A
=> Create reusable workflow called base_ci.yml

README.md
Adding a new paper to the Prompt2Model references to cite.
N/A
N/A
=> Add new reference to the Prompt2Model readme
