neulab/prompt2model

prompt2model/param_selector/__init__.py, prompt2model/param_selector/base.py, prompt2model/param_selector/mock.py
#221 removed the mock parameter selector we had, which was an accident. We should keep this module in our skeleton for when we're ready to implement it.
This PR restores that module to the code.
N/A
N/A
=> Add the mock parameter selector back in

.markdownlint.yaml, README.md, pyproject.toml
`markdownlint-cli2` was complaining about certain errors in our README that are not actually a concern. This PR suppresses those errors on a line-by-line basis.
N/A
N/A
=> Suppress spurious markdown lint errors in README

.github/workflows/ci.yml
Currently running unit tests takes a very long time, much of which is due to downloading dependencies. This PR attempts to fix this issue by adding a cache.
- [Dependency caching for github CI](https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/)
- NA
=> Cache dependencies for (hopefully) faster CI

prompt2model/__init__.py
Previously our release workflow was broken. This was because there was no `__init__.py` file in the top-level directory where `version.py` lived, so `version.py` was not copied to the release tarball. This PR fixes this issue.
- Fixes https://github.com/neulab/prompt2model/issues
- NA
=> Add top-level init file

pyproject.toml
Protobuf 4.24.1 (currently set) may cause problems in many environments with our pipeline.
N/A
N/A
=> Downgrade protobuf to 3.20.0

prompt2model/dataset_processor/base.py, tests/dataset_processor_test.py
Earlier the dataset processor took the dataset given and added two new columns, `model_input` and `model_output`. This could be problematic, if the original dataset contained columns that could not be concatenated with the generated data (e.g. numerical values).
This PR removes these columns, keeping only the two necessary.
N/A
N/A
=> Remove unnecessary columns in the dataset processor

prompt2model/dataset_retriever/__init__.py, prompt2model/dataset_retriever/base.py, prompt2model/dataset_retriever/description_dataset_retriever.py, tests/dataset_retriever_test.py
In preparation for preparing our notebook demo (https://github.com/neulab/prompt2model/issues/289), it would be nice to split off the functions that require the CLI so we can replace them with more notebook-native ways of doing things. This PR starts by doing some refactoring to make the interface to the retriever a bit more cleanly separated.
- Fixes: https://github.com/neulab/prompt2model/issues/292
- NA
=> Refactor dataset retriever to isolate CLI functions

notebook_demo.ipynb
This PR updates the dataset retrieval section of the notebook demo to remove all places where the CLI was used for input. Now all of the design decisions can be modified by changing variables in the jupyter notebook.
- This is part of #290 
- NA
=> Update instructions for retrieval

notebook_demo.ipynb, prompt2model/dataset_generator/openai_gpt.py, pyproject.toml
This fixes wording up to the dataset generator, and moves the `nest_asyncio` out of the jupyter notebook into our library.
Note that I'm reverting the wording around the `.env` file, as the current wording may still encourage people to add the key to their jupyter notebook, which is not the best practice.
- NA
=> Fix some wording and asyncio

prompt_examples.md
A few typo fixes in promp_examples.md.
* "Question Answer" should be "Question Answering"
* "Machine Reading" is a bit of an esoteric technical term, and can probably be removed.
* "Japanese-to-Python" is simpler English.
=> Wording fixes in prompt_examples.md

pyproject.toml
Bumps required Python version to 3.9 in pyproject.toml.
- Fixes https://github.com/neulab/prompt2model/issues/311
- NA
=> Bump required Python version to 3.9

.pre-commit-config.yaml, prompt2model/dataset_processor/mock.py, prompt2model/model_executor/mock.py, prompt2model/model_retriever/base.py, prompt2model/model_retriever/mock.py, prompt2model/param_selector/mock.py, prompt2model/run_locally.py, prompt2model/utils/tevatron_utils/retrieve.py
I encountered this error while trying to import OpenAIInstructionParser, TaskType. Then, I solved that issue and further checked that the same issue is present in other files too, so solved them. also, pre-commit was throwing FI58 error while merging the new changes to added a parameter in pre-commit config to ignore the particular error.
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 from prompt2model.prompt_parser import OpenAIInstructionParser, TaskType
3 prompt_spec = OpenAIInstructionParser(task_type=TaskType.TEXT_GENERATION)
4 prompt_spec.parse_from_prompt(prompt)
File ~/.pyenv/versions/3.8.17/lib/python3.8/site-packages/prompt2model/prompt_parser/__init__.py:3
1 """Import PromptSpec classes."""
2 from …
=> Fixed error in type hints

README.md, prompt2model/dataset_generator/openai_gpt.py, prompt2model/utils/openai_tools.py, pyproject.toml
Hi @neubig 
Thanks for your comment on another PR. I came across prompt2model and would love to help out if possible using LiteLLM (https://github.com/BerriAI/litellm). 
I added support for the providers listed above by replacing the chatcompletion w/ completion and chatcompletion.acreate with acompletion. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.
Would love to know if this helps.
Happy to add additional tests / update documentation, if the initial PR looks good to you.
=> Adding support for Anthropic, Cohere, TogetherAI, Aleph Alpha, Huggingface Inference Endpoints, etc.

prompt2model/dataset_generator/prompt_based.py
There's one comment with a missing article before a noun, and this PR fixes that grammar error.
N/A
N/A
=> Fix grammaticality of a single comment

prompt2model/prompt_parser/instr_parser.py, prompt2model/utils/api_tools.py
To support HuggingFace's inference API, we need to expose the "api_base" parameter for LiteLLM. This PR exposes that parameter to the APIAgent.
https://docs.litellm.ai/docs/providers/huggingface
N/A
=> Support HuggingFace's inference API

prompt2model/utils/api_tools.py, test_helpers/mock_api.py
Issue #353 found that the LiteLLM agent is now reporting that our model's request is exceeding the maximum allowable number of tokens.
This problem stems from the fact that there's a disparity between `tiktoken`'s tokenizer counts and:
1) the number of tokens that OpenAI's API perceives
2) the number of tokens that OpenAI's tokenizer playground perceives
For the full prompt parser prompt, tiktoken says there's 2569 tokens, so we set max_tokens for LiteLLM to be 4097 - 2569 = 1528
However, OpenAI's API perceives there to be 2576 tokens, which exceeds the 4097 limit, while OpenAI's tokenizer thinks there's 2862 tokens.
A naive solution here is to give a buffer; e.g. generate 300 fewer tokens than the maximum limit (so we would set max_tokens to be 1228 instead of 1528). This PR implements …
=> Add buffer in the maximum number of tokens generated (to fix #353)

prompt2model/utils/dataset_utils.py, prompt2model_demo.ipynb, prompt2model_demo.py
This PR makes it easy to set the maximum model size (in both the demo script and the demo notebook). This PR also fixes a one-line bug in the dataset retriever, for convenience.
Example of how to set the maximum model size in the demo script:
N/A
N/A
=> Configure dataset size in demo script and notebook (fixes #273)

.pre-commit-config.yaml, prompt2model/dataset_retriever/column_selection_prompt.py, prompt2model/dataset_retriever/description_dataset_retriever.py, prompt2model/prompt_parser/instr_parser.py, prompt2model/utils/parse_json_responses.py, tests/dataset_retriever_test.py
A good starting point for reviewing this PR would be: https://github.com/neulab/prompt2model/pull/359/files#diff-952ef426d80e42d77fe849ad91b5ef92bcd907ea702707fb1d9a714d9e31820cR169
-Added a file for creating the prompt for column selection, it is similar to the instr_parser_prompt file; The prompt includes incontext learning as well.
-Created a function in dataset_retriever for automatic column selection
-Also included the prompt spec to be passed in _canonicalize_dataset_by_cli_ so that I can use the instruction in column selection prompt. 
-Added tests for automatic column selection
-Modified the JSON parser file to handle responses where the JSON keys would have lists as the values (and not just strings)
-Set an explicit value for max_api in json parser incase it is not set - it was …
=> Automatic Column Selection

prompt2model/dataset_retriever/column_selection_prompt.py, prompt2model/dataset_retriever/description_dataset_retriever.py, tests/dataset_retriever_test.py
- Tried to add information about columns from huggingface, but I couldn't find anything super relevant. So I decided to just add the dataset description instead. Made the appropriate changes in the base prompt as well.
- Updated the prompt for column selection by (1) adding an example where there is a mismatch between the task and dataset chosen, so there are no relevant columns (eg using a machine translation dataset for a summarization task), and (2) swapped an old example for another one
- Fixed bug in truncate_row -- only add the "..." if len(row) > max_length
- Added support for datasets like opus100 (which have nested columns), so that these datasets can be used and we don't try to generate a dataset -- the solution was pretty straightforward, using flatten() function of huggingface …
=> Column Selection: Improvements

pyproject.toml
The protobuf version required by prompt2model was specified as 3.20.0. However this is restrictive and may cause dependency issues when used in conjunction with other libraries (eg. the latest tensorflow version requires protobuf >= 3.20.3). This was originally pinned due to certain HF models requiring a specific protobuf but that issue has since been resolved by HF (see references).
I also tested a fresh install of p2m without the protobuf pinned version and both the demo notebook and python script work as expected.
- #309 
- https://github.com/huggingface/transformers/pull/24599
=> Loosen version requirement for protobuf

pyproject.toml
Our demo script is breaking due to a change in the latest OpenAI and LiteLLM APIs, as shown by issue #377. This script pins the openai and litellm versions to versions that we have tested - we will update the code to work with the latest versions of these libraries in a future PR.
#377
N/A
=> Specify library versions for openai and litellm

prompt2model/model_retriever/description_based_retriever.py
Our current code relies on the `/tmp/` directory, which is not guaranteed to exist on non-Linux operating systems, such as Windows. This PR uses the temporary file functionality in `urllib.request.urlretrieve` to avoid explicitly assuming anything about the local file structure.
N/A
N/A
=> Use temporary file for tarball instead of tmp directory (fixes #387)

prompt2model/utils/api_tools.py, pyproject.toml, tests/prompt_parser_test.py
- ran the openai migrate script
- made migrations as per litellm breaking changes in new version
- tested the single generate function
This is high priority since the old versions of openai and litellm mean that users cannot use latest models like gpt-4-turbo since litellm is not able to map model name in such cases. Additionally, having a really old pinned version for both libraries will lead to further issues in the future.
- #394
=> Migrate to the latest openAI version
